---
title: "00.1_Real_operation_reproduction"
author: "Kerman López de Calle Etxabe"
date: "20/2/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning  = FALSE)
```

# Real operation

The operation of the rig with, Nut Position, Current consumption and Position error is depicted here.

```{r warning=FALSE }


library(magrittr)
library(ggplot2)
library(dplyr)
library(gganimate)

load(here::here('Data', 'bigdata.Rdata'))

```


```{r gif creation, message=FALSE, warning=FALSE}

real_nominal <- bigdata %>% 
  filter(Test_ID == 'train' , Load ==20, Repetition == 1, Segment ==3, Motion == 'trapezoidal')

real_nominal_long <- tidyr::gather(real_nominal, key='Signal', value = 'Value', Pos_error, Current, Setpoint ) %>% 
                      mutate(Signal = factor(Signal) , Signal = relevel(Signal, 'Setpoint',  'Pos_error', 'Current'))

levels(real_nominal_long$Signal) <- c("Setpoint (mm)", "Current (A)", "Pos. error (mm)")


evolving_signals <-   ggplot(real_nominal_long, aes(STime, Value, color = Signal)) +
                        geom_line() +
                        facet_wrap(~Signal, scales = 'free_y', dir = 'v', strip.position =  'top') +
                        xlab('Time (s)') +
                        ylab('') +
                        theme_minimal() +
                        theme(legend.position = 'horizontal') +
                        transition_reveal(STime) 
                        
                        
EMA_actuation <- animate(evolving_signals, fps = 5, end_pause = 25)
 
EMA_actuation
 

```

```{r save gif, message=TRUE, warning=TRUE}

anim_save(filename = here::here('figures', 'gifs','evoling_signal.gif'), 
            aanimation = EMA_actuation)

```



